kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30040
        hostPort: 4040
        protocol: TCP
      - containerPort: 30686
        hostPort: 16686
        protocol: TCP
  - role: worker
