// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type gvltracerGvlLastState struct {
	_           structs.HostLayout
	State       uint32
	_           [4]byte
	TimestampNs uint64
}

type gvltracerGvlThreadKey struct {
	_   structs.HostLayout
	Pid uint32
	Tid uint32
}

// loadGvltracer returns the embedded CollectionSpec for gvltracer.
func loadGvltracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GvltracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gvltracer: %w", err)
	}

	return spec, err
}

// loadGvltracerObjects loads gvltracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gvltracerObjects
//	*gvltracerPrograms
//	*gvltracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGvltracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGvltracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gvltracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gvltracerSpecs struct {
	gvltracerProgramSpecs
	gvltracerMapSpecs
	gvltracerVariableSpecs
}

// gvltracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gvltracerProgramSpecs struct {
	HandleGvlEvent *ebpf.ProgramSpec `ebpf:"handle_gvl_event"`
	HandleGvlStack *ebpf.ProgramSpec `ebpf:"handle_gvl_stack"`
}

// gvltracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gvltracerMapSpecs struct {
	GvlDropCount   *ebpf.MapSpec `ebpf:"gvl_drop_count"`
	GvlEvents      *ebpf.MapSpec `ebpf:"gvl_events"`
	GvlStackEvents *ebpf.MapSpec `ebpf:"gvl_stack_events"`
	GvlThreadState *ebpf.MapSpec `ebpf:"gvl_thread_state"`
}

// gvltracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gvltracerVariableSpecs struct {
}

// gvltracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGvltracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type gvltracerObjects struct {
	gvltracerPrograms
	gvltracerMaps
	gvltracerVariables
}

func (o *gvltracerObjects) Close() error {
	return _GvltracerClose(
		&o.gvltracerPrograms,
		&o.gvltracerMaps,
	)
}

// gvltracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGvltracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type gvltracerMaps struct {
	GvlDropCount   *ebpf.Map `ebpf:"gvl_drop_count"`
	GvlEvents      *ebpf.Map `ebpf:"gvl_events"`
	GvlStackEvents *ebpf.Map `ebpf:"gvl_stack_events"`
	GvlThreadState *ebpf.Map `ebpf:"gvl_thread_state"`
}

func (m *gvltracerMaps) Close() error {
	return _GvltracerClose(
		m.GvlDropCount,
		m.GvlEvents,
		m.GvlStackEvents,
		m.GvlThreadState,
	)
}

// gvltracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGvltracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type gvltracerVariables struct {
}

// gvltracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGvltracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type gvltracerPrograms struct {
	HandleGvlEvent *ebpf.Program `ebpf:"handle_gvl_event"`
	HandleGvlStack *ebpf.Program `ebpf:"handle_gvl_stack"`
}

func (p *gvltracerPrograms) Close() error {
	return _GvltracerClose(
		p.HandleGvlEvent,
		p.HandleGvlStack,
	)
}

func _GvltracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gvltracer_arm64_bpfel.o
var _GvltracerBytes []byte
