// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type iotracerSyscallEnter struct {
	_           structs.HostLayout
	TimestampNs uint64
	SyscallNr   uint32
	Fd          uint32
}

// loadIotracer returns the embedded CollectionSpec for iotracer.
func loadIotracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IotracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iotracer: %w", err)
	}

	return spec, err
}

// loadIotracerObjects loads iotracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iotracerObjects
//	*iotracerPrograms
//	*iotracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIotracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIotracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iotracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerSpecs struct {
	iotracerProgramSpecs
	iotracerMapSpecs
	iotracerVariableSpecs
}

// iotracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerProgramSpecs struct {
	TpSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_connect"`
	TpSysEnterRead     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite    *ebpf.ProgramSpec `ebpf:"tp_sys_enter_write"`
	TpSysExitConnect   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_connect"`
	TpSysExitRead      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto    *ebpf.ProgramSpec `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite     *ebpf.ProgramSpec `ebpf:"tp_sys_exit_write"`
}

// iotracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerMapSpecs struct {
	Inflight       *ebpf.MapSpec `ebpf:"inflight"`
	IoEvents       *ebpf.MapSpec `ebpf:"io_events"`
	TargetPids     *ebpf.MapSpec `ebpf:"target_pids"`
	TidToRubyStack *ebpf.MapSpec `ebpf:"tid_to_ruby_stack"`
}

// iotracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerVariableSpecs struct {
}

// iotracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerObjects struct {
	iotracerPrograms
	iotracerMaps
	iotracerVariables
}

func (o *iotracerObjects) Close() error {
	return _IotracerClose(
		&o.iotracerPrograms,
		&o.iotracerMaps,
	)
}

// iotracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerMaps struct {
	Inflight       *ebpf.Map `ebpf:"inflight"`
	IoEvents       *ebpf.Map `ebpf:"io_events"`
	TargetPids     *ebpf.Map `ebpf:"target_pids"`
	TidToRubyStack *ebpf.Map `ebpf:"tid_to_ruby_stack"`
}

func (m *iotracerMaps) Close() error {
	return _IotracerClose(
		m.Inflight,
		m.IoEvents,
		m.TargetPids,
		m.TidToRubyStack,
	)
}

// iotracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerVariables struct {
}

// iotracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerPrograms struct {
	TpSysEnterConnect  *ebpf.Program `ebpf:"tp_sys_enter_connect"`
	TpSysEnterRead     *ebpf.Program `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom *ebpf.Program `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto   *ebpf.Program `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite    *ebpf.Program `ebpf:"tp_sys_enter_write"`
	TpSysExitConnect   *ebpf.Program `ebpf:"tp_sys_exit_connect"`
	TpSysExitRead      *ebpf.Program `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom  *ebpf.Program `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto    *ebpf.Program `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite     *ebpf.Program `ebpf:"tp_sys_exit_write"`
}

func (p *iotracerPrograms) Close() error {
	return _IotracerClose(
		p.TpSysEnterConnect,
		p.TpSysEnterRead,
		p.TpSysEnterRecvfrom,
		p.TpSysEnterSendto,
		p.TpSysEnterWrite,
		p.TpSysExitConnect,
		p.TpSysExitRead,
		p.TpSysExitRecvfrom,
		p.TpSysExitSendto,
		p.TpSysExitWrite,
	)
}

func _IotracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iotracer_arm64_bpfel.o
var _IotracerBytes []byte
