// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type iotracerSyscallEnter struct {
	_           structs.HostLayout
	TimestampNs uint64
	SyscallNr   uint32
	Fd          uint32
}

// loadIotracer returns the embedded CollectionSpec for iotracer.
func loadIotracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IotracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iotracer: %w", err)
	}

	return spec, err
}

// loadIotracerObjects loads iotracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iotracerObjects
//	*iotracerPrograms
//	*iotracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIotracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIotracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iotracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerSpecs struct {
	iotracerProgramSpecs
	iotracerMapSpecs
	iotracerVariableSpecs
}

// iotracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerProgramSpecs struct {
	TpSysEnterAccept4   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_accept4"`
	TpSysEnterClone     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_clone"`
	TpSysEnterConnect   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_connect"`
	TpSysEnterEpollWait *ebpf.ProgramSpec `ebpf:"tp_sys_enter_epoll_wait"`
	TpSysEnterFutex     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_futex"`
	TpSysEnterGetrandom *ebpf.ProgramSpec `ebpf:"tp_sys_enter_getrandom"`
	TpSysEnterPoll      *ebpf.ProgramSpec `ebpf:"tp_sys_enter_poll"`
	TpSysEnterPpoll     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_ppoll"`
	TpSysEnterPselect6  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_pselect6"`
	TpSysEnterRead      *ebpf.ProgramSpec `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto    *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite     *ebpf.ProgramSpec `ebpf:"tp_sys_enter_write"`
	TpSysExitAccept4    *ebpf.ProgramSpec `ebpf:"tp_sys_exit_accept4"`
	TpSysExitClone      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_clone"`
	TpSysExitConnect    *ebpf.ProgramSpec `ebpf:"tp_sys_exit_connect"`
	TpSysExitEpollWait  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_epoll_wait"`
	TpSysExitFutex      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_futex"`
	TpSysExitGetrandom  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_getrandom"`
	TpSysExitPoll       *ebpf.ProgramSpec `ebpf:"tp_sys_exit_poll"`
	TpSysExitPpoll      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_ppoll"`
	TpSysExitPselect6   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_pselect6"`
	TpSysExitRead       *ebpf.ProgramSpec `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto     *ebpf.ProgramSpec `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite      *ebpf.ProgramSpec `ebpf:"tp_sys_exit_write"`
}

// iotracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerMapSpecs struct {
	Inflight   *ebpf.MapSpec `ebpf:"inflight"`
	IoEvents   *ebpf.MapSpec `ebpf:"io_events"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
}

// iotracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iotracerVariableSpecs struct {
}

// iotracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerObjects struct {
	iotracerPrograms
	iotracerMaps
	iotracerVariables
}

func (o *iotracerObjects) Close() error {
	return _IotracerClose(
		&o.iotracerPrograms,
		&o.iotracerMaps,
	)
}

// iotracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerMaps struct {
	Inflight   *ebpf.Map `ebpf:"inflight"`
	IoEvents   *ebpf.Map `ebpf:"io_events"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
}

func (m *iotracerMaps) Close() error {
	return _IotracerClose(
		m.Inflight,
		m.IoEvents,
		m.TargetPids,
	)
}

// iotracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerVariables struct {
}

// iotracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIotracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type iotracerPrograms struct {
	TpSysEnterAccept4   *ebpf.Program `ebpf:"tp_sys_enter_accept4"`
	TpSysEnterClone     *ebpf.Program `ebpf:"tp_sys_enter_clone"`
	TpSysEnterConnect   *ebpf.Program `ebpf:"tp_sys_enter_connect"`
	TpSysEnterEpollWait *ebpf.Program `ebpf:"tp_sys_enter_epoll_wait"`
	TpSysEnterFutex     *ebpf.Program `ebpf:"tp_sys_enter_futex"`
	TpSysEnterGetrandom *ebpf.Program `ebpf:"tp_sys_enter_getrandom"`
	TpSysEnterPoll      *ebpf.Program `ebpf:"tp_sys_enter_poll"`
	TpSysEnterPpoll     *ebpf.Program `ebpf:"tp_sys_enter_ppoll"`
	TpSysEnterPselect6  *ebpf.Program `ebpf:"tp_sys_enter_pselect6"`
	TpSysEnterRead      *ebpf.Program `ebpf:"tp_sys_enter_read"`
	TpSysEnterRecvfrom  *ebpf.Program `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterSendto    *ebpf.Program `ebpf:"tp_sys_enter_sendto"`
	TpSysEnterWrite     *ebpf.Program `ebpf:"tp_sys_enter_write"`
	TpSysExitAccept4    *ebpf.Program `ebpf:"tp_sys_exit_accept4"`
	TpSysExitClone      *ebpf.Program `ebpf:"tp_sys_exit_clone"`
	TpSysExitConnect    *ebpf.Program `ebpf:"tp_sys_exit_connect"`
	TpSysExitEpollWait  *ebpf.Program `ebpf:"tp_sys_exit_epoll_wait"`
	TpSysExitFutex      *ebpf.Program `ebpf:"tp_sys_exit_futex"`
	TpSysExitGetrandom  *ebpf.Program `ebpf:"tp_sys_exit_getrandom"`
	TpSysExitPoll       *ebpf.Program `ebpf:"tp_sys_exit_poll"`
	TpSysExitPpoll      *ebpf.Program `ebpf:"tp_sys_exit_ppoll"`
	TpSysExitPselect6   *ebpf.Program `ebpf:"tp_sys_exit_pselect6"`
	TpSysExitRead       *ebpf.Program `ebpf:"tp_sys_exit_read"`
	TpSysExitRecvfrom   *ebpf.Program `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitSendto     *ebpf.Program `ebpf:"tp_sys_exit_sendto"`
	TpSysExitWrite      *ebpf.Program `ebpf:"tp_sys_exit_write"`
}

func (p *iotracerPrograms) Close() error {
	return _IotracerClose(
		p.TpSysEnterAccept4,
		p.TpSysEnterClone,
		p.TpSysEnterConnect,
		p.TpSysEnterEpollWait,
		p.TpSysEnterFutex,
		p.TpSysEnterGetrandom,
		p.TpSysEnterPoll,
		p.TpSysEnterPpoll,
		p.TpSysEnterPselect6,
		p.TpSysEnterRead,
		p.TpSysEnterRecvfrom,
		p.TpSysEnterSendto,
		p.TpSysEnterWrite,
		p.TpSysExitAccept4,
		p.TpSysExitClone,
		p.TpSysExitConnect,
		p.TpSysExitEpollWait,
		p.TpSysExitFutex,
		p.TpSysExitGetrandom,
		p.TpSysExitPoll,
		p.TpSysExitPpoll,
		p.TpSysExitPselect6,
		p.TpSysExitRead,
		p.TpSysExitRecvfrom,
		p.TpSysExitSendto,
		p.TpSysExitWrite,
	)
}

func _IotracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iotracer_x86_bpfel.o
var _IotracerBytes []byte
