//go:build linux

package bpf

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/schlubbi/rbscope/collector/pkg/collector"
)

// bpfObjects mirrors the struct that bpf2go generates from ruby_reader.c.
// Field tags must match the ELF symbol/section names produced by clang:
//   - "events"              → BPF map name from SEC(".maps")
//   - "handle_ruby_sample"  → C function name in SEC("uprobe/ruby_sample")
type bpfObjects struct {
	Events           *ebpf.Map     `ebpf:"events"`
	HandleRubySample *ebpf.Program `ebpf:"handle_ruby_sample"`
}

func (o *bpfObjects) Close() error {
	if o.Events != nil {
		_ = o.Events.Close()
	}
	if o.HandleRubySample != nil {
		_ = o.HandleRubySample.Close()
	}
	return nil
}

// RealBPF is the Linux eBPF-backed implementation of collector.BPFProgram.
type RealBPF struct {
	objPath    string
	objs       bpfObjects
	reader     *ringbuf.Reader
	links      []link.Link
	ioObjs     *iotracerObjects
	ioReader   *ringbuf.Reader
	ioLinks    []link.Link
	readToggle bool // alternates reads between ruby and io ring buffers
}

// Compile-time interface check.
var _ collector.BPFProgram = (*RealBPF)(nil)

// NewRealBPF returns a new RealBPF ready to be loaded.
// objPath is the path to the compiled BPF ELF object (e.g. ruby_reader.o).
// If empty, the embedded BPF bytecode from bpf2go is used.
func NewRealBPF(objPath string) (*RealBPF, error) {
	return &RealBPF{objPath: objPath}, nil
}

// Load opens the compiled BPF ELF and creates a ring-buffer reader.
func (r *RealBPF) Load() error {
	var spec *ebpf.CollectionSpec
	var err error

	if r.objPath != "" {
		spec, err = ebpf.LoadCollectionSpec(r.objPath)
		if err != nil {
			return fmt.Errorf("load bpf spec from %s: %w", r.objPath, err)
		}
	} else {
		// Use the embedded BPF bytecode generated by bpf2go
		spec, err = loadRbscope()
		if err != nil {
			return fmt.Errorf("load embedded bpf spec: %w", err)
		}
	}

	if err := spec.LoadAndAssign(&r.objs, nil); err != nil {
		return fmt.Errorf("load bpf objects: %w", err)
	}
	rd, err := ringbuf.NewReader(r.objs.Events)
	if err != nil {
		r.objs.Close() //nolint:errcheck // cleanup on error path
		return fmt.Errorf("open ring buffer: %w", err)
	}
	r.reader = rd

	// Load io_tracer for enriched I/O events with FD resolution
	if err := r.loadIOTracer(); err != nil {
		// IO tracing is optional — log but don't fail
		fmt.Fprintf(os.Stderr, "rbscope: io_tracer load skipped: %v\n", err)
	}

	return nil
}

// loadIOTracer loads the io_tracer BPF program and attaches syscall tracepoints.
func (r *RealBPF) loadIOTracer() error {
	ioObjs := &iotracerObjects{}
	if err := loadIotracerObjects(ioObjs, nil); err != nil {
		return fmt.Errorf("load io_tracer: %w", err)
	}
	r.ioObjs = ioObjs

	rd, err := ringbuf.NewReader(ioObjs.IoEvents)
	if err != nil {
		ioObjs.Close() //nolint:errcheck
		r.ioObjs = nil
		return fmt.Errorf("open io ring buffer: %w", err)
	}
	r.ioReader = rd

	// Attach syscall tracepoints
	type tpAttach struct {
		name string
		prog *ebpf.Program
	}
	tracepoints := []tpAttach{
		{"syscalls/sys_enter_read", ioObjs.TpSysEnterRead},
		{"syscalls/sys_exit_read", ioObjs.TpSysExitRead},
		{"syscalls/sys_enter_write", ioObjs.TpSysEnterWrite},
		{"syscalls/sys_exit_write", ioObjs.TpSysExitWrite},
		{"syscalls/sys_enter_sendto", ioObjs.TpSysEnterSendto},
		{"syscalls/sys_exit_sendto", ioObjs.TpSysExitSendto},
		{"syscalls/sys_enter_recvfrom", ioObjs.TpSysEnterRecvfrom},
		{"syscalls/sys_exit_recvfrom", ioObjs.TpSysExitRecvfrom},
		{"syscalls/sys_enter_connect", ioObjs.TpSysEnterConnect},
		{"syscalls/sys_exit_connect", ioObjs.TpSysExitConnect},
	}

	for _, tp := range tracepoints {
		l, err := link.Tracepoint("syscalls", strings.TrimPrefix(tp.name, "syscalls/"), tp.prog, nil)
		if err != nil {
			return fmt.Errorf("attach tracepoint %s: %w", tp.name, err)
		}
		r.ioLinks = append(r.ioLinks, l)
	}

	return nil
}

// AttachPID attaches a uprobe to the rbscope shared library mapped into the
// target process. It scans /proc/{pid}/maps to locate the library rather
// than assuming a fixed install path. Also adds the PID to the io_tracer's
// target_pids map for syscall filtering.
func (r *RealBPF) AttachPID(pid uint32) error {
	binPath, err := findRbscopeLibrary(pid)
	if err != nil {
		return fmt.Errorf("locate rbscope library for pid %d: %w", pid, err)
	}

	ex, err := link.OpenExecutable(binPath)
	if err != nil {
		return fmt.Errorf("open executable %s: %w", binPath, err)
	}

	// Attach uprobe to __rbscope_probe_ruby_sample — the USDT probe site
	// fired by the gem's postponed job callback with serialized stack data.
	l, err := ex.Uprobe("__rbscope_probe_ruby_sample", r.objs.HandleRubySample, &link.UprobeOptions{PID: int(pid)})
	if err != nil {
		return fmt.Errorf("attach uprobe pid %d: %w", pid, err)
	}
	r.links = append(r.links, l)

	// Add PID to io_tracer's target_pids map (if io_tracer is loaded)
	if r.ioObjs != nil {
		val := uint8(1)
		if err := r.ioObjs.TargetPids.Put(pid, val); err != nil {
			// Non-fatal: io tracing just won't filter this PID
			fmt.Fprintf(os.Stderr, "rbscope: add pid %d to io target_pids: %v\n", pid, err)
		}
	}

	return nil
}

// findRbscopeLibrary scans /proc/{pid}/maps for a memory-mapped shared object
// containing "rbscope" in its path. This handles both gem-installed paths
// (e.g. .../lib/rbscope/rbscope.bundle) and system paths (/usr/lib/librbscope.so).
func findRbscopeLibrary(pid uint32) (string, error) {
	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	f, err := os.Open(mapsPath) // #nosec G304 -- path derived from PID, reads /proc
	if err != nil {
		return "", fmt.Errorf("open %s: %w", mapsPath, err)
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		// /proc/pid/maps format: addr perms offset dev inode pathname
		// We look for executable mappings (r-xp) containing "rbscope"
		fields := strings.Fields(line)
		if len(fields) < 6 {
			continue
		}
		perms := fields[1]
		pathname := fields[len(fields)-1]

		if !strings.Contains(perms, "x") {
			continue
		}
		if strings.Contains(pathname, "rbscope") &&
			(strings.HasSuffix(pathname, ".so") || strings.HasSuffix(pathname, ".bundle")) {
			// Return the path as seen from the host via /proc/{pid}/root
			return fmt.Sprintf("/proc/%d/root%s", pid, pathname), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan %s: %w", mapsPath, err)
	}
	return "", fmt.Errorf("rbscope library not found in %s", mapsPath)
}

// DetachPID detaches all uprobes for the given PID and removes it from
// the io_tracer target_pids map.
func (r *RealBPF) DetachPID(_ uint32) error {
	remaining := r.links[:0]
	for _, l := range r.links {
		if err := l.Close(); err != nil {
			remaining = append(remaining, l)
		}
	}
	r.links = remaining

	// Remove PID from io_tracer target_pids
	// Note: DetachPID receives _ uint32 (unused param) — using the signature
	// as-is means we can't remove specific PIDs. This is a pre-existing
	// issue in the interface; for now, io_tracer tracepoints remain active
	// but filter via the map.

	return nil
}

// ReadRingBuffer reads a single record from the BPF ring buffers.
// It alternates between the ruby_reader and io_tracer ring buffers
// with short poll timeouts so neither starves.
func (r *RealBPF) ReadRingBuffer(buf []byte) (int, error) {
	// Alternate which reader we try first to prevent starvation
	r.readToggle = !r.readToggle

	if r.readToggle && r.ioReader != nil {
		// Try IO reader first
		r.ioReader.SetDeadline(time.Now().Add(10 * time.Millisecond))
		record, err := r.ioReader.Read()
		if err == nil {
			n := copy(buf, record.RawSample)
			return n, nil
		}
		// Fall through to ruby reader
	}

	// Try ruby reader
	r.reader.SetDeadline(time.Now().Add(25 * time.Millisecond))
	record, err := r.reader.Read()
	if err == nil {
		n := copy(buf, record.RawSample)
		return n, nil
	}

	// If we tried ruby first, also try IO
	if !r.readToggle && r.ioReader != nil {
		r.ioReader.SetDeadline(time.Now().Add(10 * time.Millisecond))
		record, err := r.ioReader.Read()
		if err == nil {
			n := copy(buf, record.RawSample)
			return n, nil
		}
	}

	return 0, err
}

// Close releases all BPF resources.
func (r *RealBPF) Close() error {
	for _, l := range r.links {
		_ = l.Close()
	}
	for _, l := range r.ioLinks {
		_ = l.Close()
	}
	if r.reader != nil {
		_ = r.reader.Close()
	}
	if r.ioReader != nil {
		_ = r.ioReader.Close()
	}
	_ = r.objs.Close()
	if r.ioObjs != nil {
		_ = r.ioObjs.Close()
	}
	return nil
}
