//go:build linux

package bpf

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/schlubbi/rbscope/collector/pkg/collector"
)

// bpfObjects mirrors the struct that bpf2go generates from ruby_reader.c.
// Field tags must match the ELF symbol/section names produced by clang:
//   - "events"              → BPF map name from SEC(".maps")
//   - "handle_ruby_sample"  → C function name in SEC("uprobe/ruby_sample")
type bpfObjects struct {
	Events           *ebpf.Map     `ebpf:"events"`
	HandleRubySample *ebpf.Program `ebpf:"handle_ruby_sample"`
}

func (o *bpfObjects) Close() error {
	if o.Events != nil {
		o.Events.Close()
	}
	if o.HandleRubySample != nil {
		o.HandleRubySample.Close()
	}
	return nil
}

// RealBPF is the Linux eBPF-backed implementation of collector.BPFProgram.
type RealBPF struct {
	objPath string
	objs    bpfObjects
	reader  *ringbuf.Reader
	links   []link.Link
}

// Compile-time interface check.
var _ collector.BPFProgram = (*RealBPF)(nil)

// NewRealBPF returns a new RealBPF ready to be loaded.
// objPath is the path to the compiled BPF ELF object (e.g. ruby_reader.o).
// If empty, the embedded BPF bytecode from bpf2go is used.
func NewRealBPF(objPath string) (*RealBPF, error) {
	return &RealBPF{objPath: objPath}, nil
}

// Load opens the compiled BPF ELF and creates a ring-buffer reader.
func (r *RealBPF) Load() error {
	var spec *ebpf.CollectionSpec
	var err error

	if r.objPath != "" {
		spec, err = ebpf.LoadCollectionSpec(r.objPath)
		if err != nil {
			return fmt.Errorf("load bpf spec from %s: %w", r.objPath, err)
		}
	} else {
		// Use the embedded BPF bytecode generated by bpf2go
		spec, err = loadRbscope()
		if err != nil {
			return fmt.Errorf("load embedded bpf spec: %w", err)
		}
	}

	if err := spec.LoadAndAssign(&r.objs, nil); err != nil {
		return fmt.Errorf("load bpf objects: %w", err)
	}
	rd, err := ringbuf.NewReader(r.objs.Events)
	if err != nil {
		r.objs.Close()
		return fmt.Errorf("open ring buffer: %w", err)
	}
	r.reader = rd
	return nil
}

// AttachPID attaches a uprobe to the rbscope shared library mapped into the
// target process. It scans /proc/{pid}/maps to locate the library rather
// than assuming a fixed install path.
func (r *RealBPF) AttachPID(pid uint32) error {
	binPath, err := findRbscopeLibrary(pid)
	if err != nil {
		return fmt.Errorf("locate rbscope library for pid %d: %w", pid, err)
	}

	ex, err := link.OpenExecutable(binPath)
	if err != nil {
		return fmt.Errorf("open executable %s: %w", binPath, err)
	}

	// Attach uprobe to __rbscope_probe_ruby_sample — the USDT probe site
	// fired by the gem's postponed job callback with serialized stack data.
	l, err := ex.Uprobe("__rbscope_probe_ruby_sample", r.objs.HandleRubySample, &link.UprobeOptions{PID: int(pid)})
	if err != nil {
		return fmt.Errorf("attach uprobe pid %d: %w", pid, err)
	}
	r.links = append(r.links, l)
	return nil
}

// findRbscopeLibrary scans /proc/{pid}/maps for a memory-mapped shared object
// containing "rbscope" in its path. This handles both gem-installed paths
// (e.g. .../lib/rbscope/rbscope.bundle) and system paths (/usr/lib/librbscope.so).
func findRbscopeLibrary(pid uint32) (string, error) {
	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	f, err := os.Open(mapsPath) // #nosec G304 -- path derived from PID, reads /proc
	if err != nil {
		return "", fmt.Errorf("open %s: %w", mapsPath, err)
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		// /proc/pid/maps format: addr perms offset dev inode pathname
		// We look for executable mappings (r-xp) containing "rbscope"
		fields := strings.Fields(line)
		if len(fields) < 6 {
			continue
		}
		perms := fields[1]
		pathname := fields[len(fields)-1]

		if !strings.Contains(perms, "x") {
			continue
		}
		if strings.Contains(pathname, "rbscope") &&
			(strings.HasSuffix(pathname, ".so") || strings.HasSuffix(pathname, ".bundle")) {
			// Return the path as seen from the host via /proc/{pid}/root
			return fmt.Sprintf("/proc/%d/root%s", pid, pathname), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan %s: %w", mapsPath, err)
	}
	return "", fmt.Errorf("rbscope library not found in %s", mapsPath)
}

// DetachPID detaches all uprobes for the given PID.
func (r *RealBPF) DetachPID(pid uint32) error {
	remaining := r.links[:0]
	for _, l := range r.links {
		if err := l.Close(); err != nil {
			remaining = append(remaining, l)
		}
	}
	r.links = remaining
	return nil
}

// ReadRingBuffer reads a single record from the BPF ring buffer with a short
// poll timeout so the caller's event loop stays responsive.
func (r *RealBPF) ReadRingBuffer(buf []byte) (int, error) {
	r.reader.SetDeadline(time.Now().Add(50 * time.Millisecond))
	record, err := r.reader.Read()
	if err != nil {
		return 0, err
	}
	n := copy(buf, record.RawSample)
	return n, nil
}

// Close releases all BPF resources.
func (r *RealBPF) Close() error {
	for _, l := range r.links {
		_ = l.Close()
	}
	if r.reader != nil {
		_ = r.reader.Close()
	}
	_ = r.objs.Close()
	return nil
}
Close()
	}
	r.objs.Close()
	return nil
}
