// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRbscope returns the embedded CollectionSpec for rbscope.
func loadRbscope() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RbscopeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rbscope: %w", err)
	}

	return spec, err
}

// loadRbscopeObjects loads rbscope and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rbscopeObjects
//	*rbscopePrograms
//	*rbscopeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRbscopeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRbscope()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rbscopeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rbscopeSpecs struct {
	rbscopeProgramSpecs
	rbscopeMapSpecs
	rbscopeVariableSpecs
}

// rbscopeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rbscopeProgramSpecs struct {
	HandleRubyAlloc  *ebpf.ProgramSpec `ebpf:"handle_ruby_alloc"`
	HandleRubySample *ebpf.ProgramSpec `ebpf:"handle_ruby_sample"`
}

// rbscopeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rbscopeMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Scratch *ebpf.MapSpec `ebpf:"scratch"`
}

// rbscopeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rbscopeVariableSpecs struct {
}

// rbscopeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRbscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type rbscopeObjects struct {
	rbscopePrograms
	rbscopeMaps
	rbscopeVariables
}

func (o *rbscopeObjects) Close() error {
	return _RbscopeClose(
		&o.rbscopePrograms,
		&o.rbscopeMaps,
	)
}

// rbscopeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRbscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type rbscopeMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Scratch *ebpf.Map `ebpf:"scratch"`
}

func (m *rbscopeMaps) Close() error {
	return _RbscopeClose(
		m.Events,
		m.Scratch,
	)
}

// rbscopeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRbscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type rbscopeVariables struct {
}

// rbscopePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRbscopeObjects or ebpf.CollectionSpec.LoadAndAssign.
type rbscopePrograms struct {
	HandleRubyAlloc  *ebpf.Program `ebpf:"handle_ruby_alloc"`
	HandleRubySample *ebpf.Program `ebpf:"handle_ruby_sample"`
}

func (p *rbscopePrograms) Close() error {
	return _RbscopeClose(
		p.HandleRubyAlloc,
		p.HandleRubySample,
	)
}

func _RbscopeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rbscope_arm64_bpfel.o
var _RbscopeBytes []byte
