// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSchedtracer returns the embedded CollectionSpec for schedtracer.
func loadSchedtracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedtracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load schedtracer: %w", err)
	}

	return spec, err
}

// loadSchedtracerObjects loads schedtracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*schedtracerObjects
//	*schedtracerPrograms
//	*schedtracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSchedtracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSchedtracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// schedtracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedtracerSpecs struct {
	schedtracerProgramSpecs
	schedtracerMapSpecs
	schedtracerVariableSpecs
}

// schedtracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedtracerProgramSpecs struct {
	TpSchedSwitch *ebpf.ProgramSpec `ebpf:"tp_sched_switch"`
}

// schedtracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedtracerMapSpecs struct {
	OffcpuStart *ebpf.MapSpec `ebpf:"offcpu_start"`
	SchedEvents *ebpf.MapSpec `ebpf:"sched_events"`
	TargetPids  *ebpf.MapSpec `ebpf:"target_pids"`
}

// schedtracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedtracerVariableSpecs struct {
}

// schedtracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSchedtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedtracerObjects struct {
	schedtracerPrograms
	schedtracerMaps
	schedtracerVariables
}

func (o *schedtracerObjects) Close() error {
	return _SchedtracerClose(
		&o.schedtracerPrograms,
		&o.schedtracerMaps,
	)
}

// schedtracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSchedtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedtracerMaps struct {
	OffcpuStart *ebpf.Map `ebpf:"offcpu_start"`
	SchedEvents *ebpf.Map `ebpf:"sched_events"`
	TargetPids  *ebpf.Map `ebpf:"target_pids"`
}

func (m *schedtracerMaps) Close() error {
	return _SchedtracerClose(
		m.OffcpuStart,
		m.SchedEvents,
		m.TargetPids,
	)
}

// schedtracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSchedtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedtracerVariables struct {
}

// schedtracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSchedtracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedtracerPrograms struct {
	TpSchedSwitch *ebpf.Program `ebpf:"tp_sched_switch"`
}

func (p *schedtracerPrograms) Close() error {
	return _SchedtracerClose(
		p.TpSchedSwitch,
	)
}

func _SchedtracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed schedtracer_x86_bpfel.o
var _SchedtracerBytes []byte
