// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type stackwalkerPidConfig struct {
	_           structs.HostLayout
	EcAddr      uint64
	LibrubyBase uint64
}

type stackwalkerRubyOffsets struct {
	_                  structs.HostLayout
	EcVmStack          uint32
	EcVmStackSize      uint32
	EcCfp              uint32
	CfpPc              uint32
	CfpSp              uint32
	CfpIseq            uint32
	CfpSelf            uint32
	CfpEp              uint32
	CfpSizeof          uint32
	IseqBody           uint32
	BodyLocation       uint32
	BodyIseqEncoded    uint32
	LocPathobj         uint32
	LocBaseLabel       uint32
	LocLabel           uint32
	LocFirstLineno     uint32
	ThreadEc           uint32
	VmRactorMainThread uint32
	RstringLen         uint32
	RstringHeapPtr     uint32
	RstringEmbedStart  uint32
	Pad                uint32
	RstringNoembed     uint64
}

type stackwalkerStackWalkerEvent struct {
	_              structs.HostLayout
	EventType      uint32
	Pid            uint32
	Tid            uint32
	NumFrames      uint32
	TimestampNs    uint64
	ThreadId       uint64
	NativeStackLen uint32
	Pad            uint32
	Frames         [128]struct {
		_        structs.HostLayout
		IseqAddr uint64
		Pc       uint64
		SelfVal  uint64
		IsCfunc  uint32
		Pad      uint32
	}
	NativeStack [512]uint8
}

// loadStackwalker returns the embedded CollectionSpec for stackwalker.
func loadStackwalker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StackwalkerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load stackwalker: %w", err)
	}

	return spec, err
}

// loadStackwalkerObjects loads stackwalker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*stackwalkerObjects
//	*stackwalkerPrograms
//	*stackwalkerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStackwalkerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStackwalker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// stackwalkerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stackwalkerSpecs struct {
	stackwalkerProgramSpecs
	stackwalkerMapSpecs
	stackwalkerVariableSpecs
}

// stackwalkerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stackwalkerProgramSpecs struct {
	HandleRubySample *ebpf.ProgramSpec `ebpf:"handle_ruby_sample"`
}

// stackwalkerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stackwalkerMapSpecs struct {
	PidConfigs        *ebpf.MapSpec `ebpf:"pid_configs"`
	RubyOffsetsMap    *ebpf.MapSpec `ebpf:"ruby_offsets_map"`
	Scratch           *ebpf.MapSpec `ebpf:"scratch"`
	StackWalkerEvents *ebpf.MapSpec `ebpf:"stack_walker_events"`
}

// stackwalkerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stackwalkerVariableSpecs struct {
}

// stackwalkerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStackwalkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type stackwalkerObjects struct {
	stackwalkerPrograms
	stackwalkerMaps
	stackwalkerVariables
}

func (o *stackwalkerObjects) Close() error {
	return _StackwalkerClose(
		&o.stackwalkerPrograms,
		&o.stackwalkerMaps,
	)
}

// stackwalkerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStackwalkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type stackwalkerMaps struct {
	PidConfigs        *ebpf.Map `ebpf:"pid_configs"`
	RubyOffsetsMap    *ebpf.Map `ebpf:"ruby_offsets_map"`
	Scratch           *ebpf.Map `ebpf:"scratch"`
	StackWalkerEvents *ebpf.Map `ebpf:"stack_walker_events"`
}

func (m *stackwalkerMaps) Close() error {
	return _StackwalkerClose(
		m.PidConfigs,
		m.RubyOffsetsMap,
		m.Scratch,
		m.StackWalkerEvents,
	)
}

// stackwalkerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStackwalkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type stackwalkerVariables struct {
}

// stackwalkerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStackwalkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type stackwalkerPrograms struct {
	HandleRubySample *ebpf.Program `ebpf:"handle_ruby_sample"`
}

func (p *stackwalkerPrograms) Close() error {
	return _StackwalkerClose(
		p.HandleRubySample,
	)
}

func _StackwalkerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stackwalker_arm64_bpfel.o
var _StackwalkerBytes []byte
