// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rbscope.proto

package rbscopepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OffCPUReason int32

const (
	OffCPUReason_OFF_CPU_UNKNOWN         OffCPUReason = 0
	OffCPUReason_OFF_CPU_IO_BLOCKED      OffCPUReason = 1
	OffCPUReason_OFF_CPU_GVL_WAIT        OffCPUReason = 2
	OffCPUReason_OFF_CPU_MUTEX           OffCPUReason = 3
	OffCPUReason_OFF_CPU_PREEMPTED       OffCPUReason = 4
	OffCPUReason_OFF_CPU_VOLUNTARY_SLEEP OffCPUReason = 5
)

// Enum value maps for OffCPUReason.
var (
	OffCPUReason_name = map[int32]string{
		0: "OFF_CPU_UNKNOWN",
		1: "OFF_CPU_IO_BLOCKED",
		2: "OFF_CPU_GVL_WAIT",
		3: "OFF_CPU_MUTEX",
		4: "OFF_CPU_PREEMPTED",
		5: "OFF_CPU_VOLUNTARY_SLEEP",
	}
	OffCPUReason_value = map[string]int32{
		"OFF_CPU_UNKNOWN":         0,
		"OFF_CPU_IO_BLOCKED":      1,
		"OFF_CPU_GVL_WAIT":        2,
		"OFF_CPU_MUTEX":           3,
		"OFF_CPU_PREEMPTED":       4,
		"OFF_CPU_VOLUNTARY_SLEEP": 5,
	}
)

func (x OffCPUReason) Enum() *OffCPUReason {
	p := new(OffCPUReason)
	*p = x
	return p
}

func (x OffCPUReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OffCPUReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbscope_proto_enumTypes[0].Descriptor()
}

func (OffCPUReason) Type() protoreflect.EnumType {
	return &file_proto_rbscope_proto_enumTypes[0]
}

func (x OffCPUReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OffCPUReason.Descriptor instead.
func (OffCPUReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{0}
}

// GVL state as observed from thread event hooks.
type GVLState int32

const (
	GVLState_GVL_STATE_UNKNOWN   GVLState = 0
	GVLState_GVL_STATE_RUNNING   GVLState = 1 // Thread holds GVL (from RESUMED event)
	GVLState_GVL_STATE_STALLED   GVLState = 2 // Thread waiting for GVL (from READY event)
	GVLState_GVL_STATE_SUSPENDED GVLState = 3 // Thread released GVL voluntarily (from SUSPENDED event)
)

// Enum value maps for GVLState.
var (
	GVLState_name = map[int32]string{
		0: "GVL_STATE_UNKNOWN",
		1: "GVL_STATE_RUNNING",
		2: "GVL_STATE_STALLED",
		3: "GVL_STATE_SUSPENDED",
	}
	GVLState_value = map[string]int32{
		"GVL_STATE_UNKNOWN":   0,
		"GVL_STATE_RUNNING":   1,
		"GVL_STATE_STALLED":   2,
		"GVL_STATE_SUSPENDED": 3,
	}
)

func (x GVLState) Enum() *GVLState {
	p := new(GVLState)
	*p = x
	return p
}

func (x GVLState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GVLState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbscope_proto_enumTypes[1].Descriptor()
}

func (GVLState) Type() protoreflect.EnumType {
	return &file_proto_rbscope_proto_enumTypes[1]
}

func (x GVLState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GVLState.Descriptor instead.
func (GVLState) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{1}
}

type ThreadState int32

const (
	ThreadState_THREAD_STATE_UNKNOWN           ThreadState = 0
	ThreadState_THREAD_STATE_RUNNING           ThreadState = 1 // on-CPU, executing Ruby code
	ThreadState_THREAD_STATE_OFF_CPU_IO        ThreadState = 2 // blocked on I/O syscall
	ThreadState_THREAD_STATE_OFF_CPU_GVL       ThreadState = 3 // waiting for GVL
	ThreadState_THREAD_STATE_OFF_CPU_MUTEX     ThreadState = 4 // waiting on a Ruby mutex
	ThreadState_THREAD_STATE_OFF_CPU_SLEEP     ThreadState = 5 // voluntary sleep
	ThreadState_THREAD_STATE_OFF_CPU_PREEMPTED ThreadState = 6
	ThreadState_THREAD_STATE_OFF_CPU_UNKNOWN   ThreadState = 7
	ThreadState_THREAD_STATE_GC                ThreadState = 8 // garbage collection
	ThreadState_THREAD_STATE_IDLE              ThreadState = 9 // no work
)

// Enum value maps for ThreadState.
var (
	ThreadState_name = map[int32]string{
		0: "THREAD_STATE_UNKNOWN",
		1: "THREAD_STATE_RUNNING",
		2: "THREAD_STATE_OFF_CPU_IO",
		3: "THREAD_STATE_OFF_CPU_GVL",
		4: "THREAD_STATE_OFF_CPU_MUTEX",
		5: "THREAD_STATE_OFF_CPU_SLEEP",
		6: "THREAD_STATE_OFF_CPU_PREEMPTED",
		7: "THREAD_STATE_OFF_CPU_UNKNOWN",
		8: "THREAD_STATE_GC",
		9: "THREAD_STATE_IDLE",
	}
	ThreadState_value = map[string]int32{
		"THREAD_STATE_UNKNOWN":           0,
		"THREAD_STATE_RUNNING":           1,
		"THREAD_STATE_OFF_CPU_IO":        2,
		"THREAD_STATE_OFF_CPU_GVL":       3,
		"THREAD_STATE_OFF_CPU_MUTEX":     4,
		"THREAD_STATE_OFF_CPU_SLEEP":     5,
		"THREAD_STATE_OFF_CPU_PREEMPTED": 6,
		"THREAD_STATE_OFF_CPU_UNKNOWN":   7,
		"THREAD_STATE_GC":                8,
		"THREAD_STATE_IDLE":              9,
	}
)

func (x ThreadState) Enum() *ThreadState {
	p := new(ThreadState)
	*p = x
	return p
}

func (x ThreadState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreadState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbscope_proto_enumTypes[2].Descriptor()
}

func (ThreadState) Type() protoreflect.EnumType {
	return &file_proto_rbscope_proto_enumTypes[2]
}

func (x ThreadState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreadState.Descriptor instead.
func (ThreadState) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{2}
}

// FdType classifies what a file descriptor backs.
type FdType int32

const (
	FdType_FD_UNKNOWN FdType = 0
	FdType_FD_FILE    FdType = 1
	FdType_FD_TCP     FdType = 2
	FdType_FD_UDP     FdType = 3
	FdType_FD_UNIX    FdType = 4
	FdType_FD_PIPE    FdType = 5
)

// Enum value maps for FdType.
var (
	FdType_name = map[int32]string{
		0: "FD_UNKNOWN",
		1: "FD_FILE",
		2: "FD_TCP",
		3: "FD_UDP",
		4: "FD_UNIX",
		5: "FD_PIPE",
	}
	FdType_value = map[string]int32{
		"FD_UNKNOWN": 0,
		"FD_FILE":    1,
		"FD_TCP":     2,
		"FD_UDP":     3,
		"FD_UNIX":    4,
		"FD_PIPE":    5,
	}
)

func (x FdType) Enum() *FdType {
	p := new(FdType)
	*p = x
	return p
}

func (x FdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FdType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbscope_proto_enumTypes[3].Descriptor()
}

func (FdType) Type() protoreflect.EnumType {
	return &file_proto_rbscope_proto_enumTypes[3]
}

func (x FdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FdType.Descriptor instead.
func (FdType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{3}
}

// StackFrame is a single frame in a call stack.
// FrameType distinguishes Ruby-level frames from native C frames.
type FrameType int32

const (
	FrameType_FRAME_TYPE_RUBY   FrameType = 0 // Ruby-level frame (from gem's rb_profile_thread_frames)
	FrameType_FRAME_TYPE_NATIVE FrameType = 1 // Native C/C++ frame (from BPF bpf_get_stack)
	FrameType_FRAME_TYPE_CFUNC  FrameType = 2 // Ruby C extension function (boundary between Ruby and native)
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_RUBY",
		1: "FRAME_TYPE_NATIVE",
		2: "FRAME_TYPE_CFUNC",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_RUBY":   0,
		"FRAME_TYPE_NATIVE": 1,
		"FRAME_TYPE_CFUNC":  2,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rbscope_proto_enumTypes[4].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_proto_rbscope_proto_enumTypes[4]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{4}
}

// Capture is rbscope's canonical internal data model. A single capture
// represents one flush window (typically 10s) of profiling data for one
// process, organized as per-thread timelines with cross-referenced events.
type Capture struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *CaptureHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// String table for deduplication (function names, paths, syscall names,
	// fd descriptions, service names). Index 0 is always the empty string.
	StringTable []string `protobuf:"bytes,2,rep,name=string_table,json=stringTable,proto3" json:"string_table,omitempty"`
	// Frame table — deduplicated stack frames. Referenced by index from
	// Sample.frame_ids. Built by the collector from inline format v2 data.
	FrameTable []*StackFrame `protobuf:"bytes,3,rep,name=frame_table,json=frameTable,proto3" json:"frame_table,omitempty"`
	// Per-thread timelines — the core data structure.
	Threads []*ThreadTimeline `protobuf:"bytes,4,rep,name=threads,proto3" json:"threads,omitempty"`
	// Categories for UI rendering (matches Gecko's category concept).
	Categories    []*Category `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capture) Reset() {
	*x = Capture{}
	mi := &file_proto_rbscope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capture) ProtoMessage() {}

func (x *Capture) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capture.ProtoReflect.Descriptor instead.
func (*Capture) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{0}
}

func (x *Capture) GetHeader() *CaptureHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Capture) GetStringTable() []string {
	if x != nil {
		return x.StringTable
	}
	return nil
}

func (x *Capture) GetFrameTable() []*StackFrame {
	if x != nil {
		return x.FrameTable
	}
	return nil
}

func (x *Capture) GetThreads() []*ThreadTimeline {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *Capture) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CaptureHeader struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // proto version (2 for this format)
	ServiceName       string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Hostname          string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid               uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	StartTimeNs       uint64                 `protobuf:"varint,5,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"` // wall-clock start of capture window
	EndTimeNs         uint64                 `protobuf:"varint,6,opt,name=end_time_ns,json=endTimeNs,proto3" json:"end_time_ns,omitempty"`       // wall-clock end of capture window
	SampleFrequencyHz uint32                 `protobuf:"varint,7,opt,name=sample_frequency_hz,json=sampleFrequencyHz,proto3" json:"sample_frequency_hz,omitempty"`
	RubyVersion       string                 `protobuf:"bytes,8,opt,name=ruby_version,json=rubyVersion,proto3" json:"ruby_version,omitempty"`          // e.g. "4.0.0"
	RbscopeVersion    string                 `protobuf:"bytes,9,opt,name=rbscope_version,json=rbscopeVersion,proto3" json:"rbscope_version,omitempty"` // gem + collector version
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaptureHeader) Reset() {
	*x = CaptureHeader{}
	mi := &file_proto_rbscope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureHeader) ProtoMessage() {}

func (x *CaptureHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureHeader.ProtoReflect.Descriptor instead.
func (*CaptureHeader) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{1}
}

func (x *CaptureHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CaptureHeader) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CaptureHeader) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CaptureHeader) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CaptureHeader) GetStartTimeNs() uint64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *CaptureHeader) GetEndTimeNs() uint64 {
	if x != nil {
		return x.EndTimeNs
	}
	return 0
}

func (x *CaptureHeader) GetSampleFrequencyHz() uint32 {
	if x != nil {
		return x.SampleFrequencyHz
	}
	return 0
}

func (x *CaptureHeader) GetRubyVersion() string {
	if x != nil {
		return x.RubyVersion
	}
	return ""
}

func (x *CaptureHeader) GetRbscopeVersion() string {
	if x != nil {
		return x.RbscopeVersion
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // "CPU", "I/O", "GVL", "GC", "Idle"
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"` // for rendering: "blue", "orange", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_proto_rbscope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// ThreadTimeline groups all events for a single native thread. The collector
// builds this by dispatching decoded BPF events to the right thread based
// on TID. Events within each list are sorted by timestamp.
type ThreadTimeline struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThreadId        uint32                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`                        // native TID (from BPF)
	RubyThreadValue uint64                 `protobuf:"varint,2,opt,name=ruby_thread_value,json=rubyThreadValue,proto3" json:"ruby_thread_value,omitempty"` // Ruby thread VALUE for cross-ref
	ThreadNameIdx   uint32                 `protobuf:"varint,3,opt,name=thread_name_idx,json=threadNameIdx,proto3" json:"thread_name_idx,omitempty"`       // index into string_table
	// Periodic stack samples (from the gem's 99Hz sampler)
	Samples []*Sample `protobuf:"bytes,4,rep,name=samples,proto3" json:"samples,omitempty"`
	// Kernel-observed events
	IoEvents    []*IOEvent    `protobuf:"bytes,5,rep,name=io_events,json=ioEvents,proto3" json:"io_events,omitempty"`
	SchedEvents []*SchedEvent `protobuf:"bytes,6,rep,name=sched_events,json=schedEvents,proto3" json:"sched_events,omitempty"`
	// Ruby-level events
	SpanEvents  []*SpanEvent        `protobuf:"bytes,7,rep,name=span_events,json=spanEvents,proto3" json:"span_events,omitempty"`
	GvlEvents   []*GVLEvent         `protobuf:"bytes,8,rep,name=gvl_events,json=gvlEvents,proto3" json:"gvl_events,omitempty"`
	Allocations []*AllocationSample `protobuf:"bytes,9,rep,name=allocations,proto3" json:"allocations,omitempty"`
	// Derived thread state timeline — built by the collector from the
	// combination of sched, I/O, GVL, and sample events.
	States []*ThreadStateInterval `protobuf:"bytes,10,rep,name=states,proto3" json:"states,omitempty"`
	// GVL state changes — raw events from BPF gvl_tracer
	GvlStateChanges []*GVLStateChange `protobuf:"bytes,11,rep,name=gvl_state_changes,json=gvlStateChanges,proto3" json:"gvl_state_changes,omitempty"`
	// GVL state intervals — continuous non-overlapping intervals computed
	// from gvl_state_changes by the Go state machine. Powers the
	// barber-pole visualization in Firefox Profiler.
	GvlIntervals  []*GVLStateInterval `protobuf:"bytes,12,rep,name=gvl_intervals,json=gvlIntervals,proto3" json:"gvl_intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadTimeline) Reset() {
	*x = ThreadTimeline{}
	mi := &file_proto_rbscope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadTimeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadTimeline) ProtoMessage() {}

func (x *ThreadTimeline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadTimeline.ProtoReflect.Descriptor instead.
func (*ThreadTimeline) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{3}
}

func (x *ThreadTimeline) GetThreadId() uint32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *ThreadTimeline) GetRubyThreadValue() uint64 {
	if x != nil {
		return x.RubyThreadValue
	}
	return 0
}

func (x *ThreadTimeline) GetThreadNameIdx() uint32 {
	if x != nil {
		return x.ThreadNameIdx
	}
	return 0
}

func (x *ThreadTimeline) GetSamples() []*Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *ThreadTimeline) GetIoEvents() []*IOEvent {
	if x != nil {
		return x.IoEvents
	}
	return nil
}

func (x *ThreadTimeline) GetSchedEvents() []*SchedEvent {
	if x != nil {
		return x.SchedEvents
	}
	return nil
}

func (x *ThreadTimeline) GetSpanEvents() []*SpanEvent {
	if x != nil {
		return x.SpanEvents
	}
	return nil
}

func (x *ThreadTimeline) GetGvlEvents() []*GVLEvent {
	if x != nil {
		return x.GvlEvents
	}
	return nil
}

func (x *ThreadTimeline) GetAllocations() []*AllocationSample {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *ThreadTimeline) GetStates() []*ThreadStateInterval {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ThreadTimeline) GetGvlStateChanges() []*GVLStateChange {
	if x != nil {
		return x.GvlStateChanges
	}
	return nil
}

func (x *ThreadTimeline) GetGvlIntervals() []*GVLStateInterval {
	if x != nil {
		return x.GvlIntervals
	}
	return nil
}

// Sample is a single stack sample from the gem's postponed-job sampler.
type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	FrameIds      []uint32               `protobuf:"varint,2,rep,packed,name=frame_ids,json=frameIds,proto3" json:"frame_ids,omitempty"`  // indices into Capture.frame_table, leaf first
	OtelContext   *OTelContext           `protobuf:"bytes,3,opt,name=otel_context,json=otelContext,proto3" json:"otel_context,omitempty"` // trace/span active at sample time (optional)
	Weight        uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`                             // for dynamic sampling rate (default 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_proto_rbscope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{4}
}

func (x *Sample) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Sample) GetFrameIds() []uint32 {
	if x != nil {
		return x.FrameIds
	}
	return nil
}

func (x *Sample) GetOtelContext() *OTelContext {
	if x != nil {
		return x.OtelContext
	}
	return nil
}

func (x *Sample) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// IOEvent is an I/O operation observed by BPF io_tracer.
type IOEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SyscallIdx  uint32                 `protobuf:"varint,2,opt,name=syscall_idx,json=syscallIdx,proto3" json:"syscall_idx,omitempty"` // index into string_table: "read", "write"
	Fd          int32                  `protobuf:"varint,3,opt,name=fd,proto3" json:"fd,omitempty"`
	Bytes       uint64                 `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	LatencyNs   uint64                 `protobuf:"varint,5,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	FdInfoIdx   uint32                 `protobuf:"varint,6,opt,name=fd_info_idx,json=fdInfoIdx,proto3" json:"fd_info_idx,omitempty"` // index into string_table: "tcp:10.0.0.1:3306"
	// Cross-references (populated by timeline.Builder)
	NearestSampleIdx    uint32 `protobuf:"varint,7,opt,name=nearest_sample_idx,json=nearestSampleIdx,proto3" json:"nearest_sample_idx,omitempty"`            // closest Sample by timestamp
	CausedSchedEventIdx uint32 `protobuf:"varint,8,opt,name=caused_sched_event_idx,json=causedSchedEventIdx,proto3" json:"caused_sched_event_idx,omitempty"` // SchedEvent this I/O triggered
	// TCP performance stats (only populated for TCP sockets)
	TcpStats *TcpStats `protobuf:"bytes,9,opt,name=tcp_stats,json=tcpStats,proto3" json:"tcp_stats,omitempty"`
	// FD type classification
	FdType FdType `protobuf:"varint,10,opt,name=fd_type,json=fdType,proto3,enum=rbscope.FdType" json:"fd_type,omitempty"`
	// Socket addresses (host byte order for ports)
	LocalPort  uint32 `protobuf:"varint,11,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort uint32 `protobuf:"varint,12,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Native call stack at syscall time (from bpf_get_stack).
	// Indices into frame_table. Shows the C call chain:
	// e.g. read() ← trilogy_sock_read() ← trilogy_query()
	NativeFrameIds []uint32 `protobuf:"varint,13,rep,packed,name=native_frame_ids,json=nativeFrameIds,proto3" json:"native_frame_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IOEvent) Reset() {
	*x = IOEvent{}
	mi := &file_proto_rbscope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOEvent) ProtoMessage() {}

func (x *IOEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOEvent.ProtoReflect.Descriptor instead.
func (*IOEvent) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{5}
}

func (x *IOEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *IOEvent) GetSyscallIdx() uint32 {
	if x != nil {
		return x.SyscallIdx
	}
	return 0
}

func (x *IOEvent) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *IOEvent) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *IOEvent) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *IOEvent) GetFdInfoIdx() uint32 {
	if x != nil {
		return x.FdInfoIdx
	}
	return 0
}

func (x *IOEvent) GetNearestSampleIdx() uint32 {
	if x != nil {
		return x.NearestSampleIdx
	}
	return 0
}

func (x *IOEvent) GetCausedSchedEventIdx() uint32 {
	if x != nil {
		return x.CausedSchedEventIdx
	}
	return 0
}

func (x *IOEvent) GetTcpStats() *TcpStats {
	if x != nil {
		return x.TcpStats
	}
	return nil
}

func (x *IOEvent) GetFdType() FdType {
	if x != nil {
		return x.FdType
	}
	return FdType_FD_UNKNOWN
}

func (x *IOEvent) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *IOEvent) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *IOEvent) GetNativeFrameIds() []uint32 {
	if x != nil {
		return x.NativeFrameIds
	}
	return nil
}

// SchedEvent is an off-CPU period observed by BPF sched_tracer.
type SchedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // when the thread went back on-CPU
	OffCpuNs    uint64                 `protobuf:"varint,2,opt,name=off_cpu_ns,json=offCpuNs,proto3" json:"off_cpu_ns,omitempty"`
	// Why was this thread off-CPU? Derived from concurrent events.
	Reason OffCPUReason `protobuf:"varint,3,opt,name=reason,proto3,enum=rbscope.OffCPUReason" json:"reason,omitempty"`
	// Cross-references
	CausedByIoIdx  uint32 `protobuf:"varint,4,opt,name=caused_by_io_idx,json=causedByIoIdx,proto3" json:"caused_by_io_idx,omitempty"`    // which IOEvent caused the off-CPU
	CausedByGvlIdx uint32 `protobuf:"varint,5,opt,name=caused_by_gvl_idx,json=causedByGvlIdx,proto3" json:"caused_by_gvl_idx,omitempty"` // which GVLEvent caused the off-CPU
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedEvent) Reset() {
	*x = SchedEvent{}
	mi := &file_proto_rbscope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedEvent) ProtoMessage() {}

func (x *SchedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedEvent.ProtoReflect.Descriptor instead.
func (*SchedEvent) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{6}
}

func (x *SchedEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *SchedEvent) GetOffCpuNs() uint64 {
	if x != nil {
		return x.OffCpuNs
	}
	return 0
}

func (x *SchedEvent) GetReason() OffCPUReason {
	if x != nil {
		return x.Reason
	}
	return OffCPUReason_OFF_CPU_UNKNOWN
}

func (x *SchedEvent) GetCausedByIoIdx() uint32 {
	if x != nil {
		return x.CausedByIoIdx
	}
	return 0
}

func (x *SchedEvent) GetCausedByGvlIdx() uint32 {
	if x != nil {
		return x.CausedByGvlIdx
	}
	return 0
}

// SpanEvent represents an OTel span observed via USDT probes.
type SpanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNs       uint64                 `protobuf:"varint,1,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	DurationNs    uint64                 `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	OperationIdx  uint32                 `protobuf:"varint,3,opt,name=operation_idx,json=operationIdx,proto3" json:"operation_idx,omitempty"` // index into string_table
	ComponentIdx  uint32                 `protobuf:"varint,4,opt,name=component_idx,json=componentIdx,proto3" json:"component_idx,omitempty"` // index into string_table
	OtelContext   *OTelContext           `protobuf:"bytes,5,opt,name=otel_context,json=otelContext,proto3" json:"otel_context,omitempty"`
	FrameIds      []uint32               `protobuf:"varint,6,rep,packed,name=frame_ids,json=frameIds,proto3" json:"frame_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanEvent) Reset() {
	*x = SpanEvent{}
	mi := &file_proto_rbscope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanEvent) ProtoMessage() {}

func (x *SpanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanEvent.ProtoReflect.Descriptor instead.
func (*SpanEvent) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{7}
}

func (x *SpanEvent) GetStartNs() uint64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *SpanEvent) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *SpanEvent) GetOperationIdx() uint32 {
	if x != nil {
		return x.OperationIdx
	}
	return 0
}

func (x *SpanEvent) GetComponentIdx() uint32 {
	if x != nil {
		return x.ComponentIdx
	}
	return 0
}

func (x *SpanEvent) GetOtelContext() *OTelContext {
	if x != nil {
		return x.OtelContext
	}
	return nil
}

func (x *SpanEvent) GetFrameIds() []uint32 {
	if x != nil {
		return x.FrameIds
	}
	return nil
}

// GVLEvent represents a GVL wait period (legacy — kept for backward compat).
// Deprecated: Use GVLStateChange and GVLStateInterval instead.
type GVLEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs     uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	WaitNs          uint64                 `protobuf:"varint,2,opt,name=wait_ns,json=waitNs,proto3" json:"wait_ns,omitempty"`
	HolderThreadId  uint32                 `protobuf:"varint,3,opt,name=holder_thread_id,json=holderThreadId,proto3" json:"holder_thread_id,omitempty"`    // which thread held the GVL
	HolderSampleIdx uint32                 `protobuf:"varint,4,opt,name=holder_sample_idx,json=holderSampleIdx,proto3" json:"holder_sample_idx,omitempty"` // what the holder was doing
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GVLEvent) Reset() {
	*x = GVLEvent{}
	mi := &file_proto_rbscope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GVLEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GVLEvent) ProtoMessage() {}

func (x *GVLEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GVLEvent.ProtoReflect.Descriptor instead.
func (*GVLEvent) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{8}
}

func (x *GVLEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *GVLEvent) GetWaitNs() uint64 {
	if x != nil {
		return x.WaitNs
	}
	return 0
}

func (x *GVLEvent) GetHolderThreadId() uint32 {
	if x != nil {
		return x.HolderThreadId
	}
	return 0
}

func (x *GVLEvent) GetHolderSampleIdx() uint32 {
	if x != nil {
		return x.HolderSampleIdx
	}
	return 0
}

// GVLStateChange is a raw state transition from a BPF event.
// Sorted by timestamp within each ThreadTimeline.
type GVLStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	State         GVLState               `protobuf:"varint,2,opt,name=state,proto3,enum=rbscope.GVLState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GVLStateChange) Reset() {
	*x = GVLStateChange{}
	mi := &file_proto_rbscope_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GVLStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GVLStateChange) ProtoMessage() {}

func (x *GVLStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GVLStateChange.ProtoReflect.Descriptor instead.
func (*GVLStateChange) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{9}
}

func (x *GVLStateChange) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *GVLStateChange) GetState() GVLState {
	if x != nil {
		return x.State
	}
	return GVLState_GVL_STATE_UNKNOWN
}

// GVLStateInterval is a continuous time interval in a single GVL state.
// Computed by the Go state machine from GVLStateChange events.
// Within a thread, intervals are non-overlapping and contiguous.
type GVLStateInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNs       uint64                 `protobuf:"varint,1,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	EndNs         uint64                 `protobuf:"varint,2,opt,name=end_ns,json=endNs,proto3" json:"end_ns,omitempty"`
	State         GVLState               `protobuf:"varint,3,opt,name=state,proto3,enum=rbscope.GVLState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GVLStateInterval) Reset() {
	*x = GVLStateInterval{}
	mi := &file_proto_rbscope_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GVLStateInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GVLStateInterval) ProtoMessage() {}

func (x *GVLStateInterval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GVLStateInterval.ProtoReflect.Descriptor instead.
func (*GVLStateInterval) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{10}
}

func (x *GVLStateInterval) GetStartNs() uint64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *GVLStateInterval) GetEndNs() uint64 {
	if x != nil {
		return x.EndNs
	}
	return 0
}

func (x *GVLStateInterval) GetState() GVLState {
	if x != nil {
		return x.State
	}
	return GVLState_GVL_STATE_UNKNOWN
}

// AllocationSample is a heap allocation event (future — from heap TODO).
type AllocationSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	ObjectTypeIdx uint32                 `protobuf:"varint,2,opt,name=object_type_idx,json=objectTypeIdx,proto3" json:"object_type_idx,omitempty"` // index into string_table
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	FrameIds      []uint32               `protobuf:"varint,4,rep,packed,name=frame_ids,json=frameIds,proto3" json:"frame_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationSample) Reset() {
	*x = AllocationSample{}
	mi := &file_proto_rbscope_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationSample) ProtoMessage() {}

func (x *AllocationSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationSample.ProtoReflect.Descriptor instead.
func (*AllocationSample) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{11}
}

func (x *AllocationSample) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *AllocationSample) GetObjectTypeIdx() uint32 {
	if x != nil {
		return x.ObjectTypeIdx
	}
	return 0
}

func (x *AllocationSample) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AllocationSample) GetFrameIds() []uint32 {
	if x != nil {
		return x.FrameIds
	}
	return nil
}

// ThreadStateInterval represents what a thread was doing during a time
// interval. Built by the collector from raw events.
type ThreadStateInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNs       uint64                 `protobuf:"varint,1,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	EndNs         uint64                 `protobuf:"varint,2,opt,name=end_ns,json=endNs,proto3" json:"end_ns,omitempty"`
	State         ThreadState            `protobuf:"varint,3,opt,name=state,proto3,enum=rbscope.ThreadState" json:"state,omitempty"`
	CauseEventIdx uint32                 `protobuf:"varint,4,opt,name=cause_event_idx,json=causeEventIdx,proto3" json:"cause_event_idx,omitempty"` // index into the relevant event list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStateInterval) Reset() {
	*x = ThreadStateInterval{}
	mi := &file_proto_rbscope_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStateInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStateInterval) ProtoMessage() {}

func (x *ThreadStateInterval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStateInterval.ProtoReflect.Descriptor instead.
func (*ThreadStateInterval) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{12}
}

func (x *ThreadStateInterval) GetStartNs() uint64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *ThreadStateInterval) GetEndNs() uint64 {
	if x != nil {
		return x.EndNs
	}
	return 0
}

func (x *ThreadStateInterval) GetState() ThreadState {
	if x != nil {
		return x.State
	}
	return ThreadState_THREAD_STATE_UNKNOWN
}

func (x *ThreadStateInterval) GetCauseEventIdx() uint32 {
	if x != nil {
		return x.CauseEventIdx
	}
	return 0
}

// TcpStats captures TCP performance metrics at the time of an I/O event.
// Read from struct tcp_sock via BPF CO-RE.
type TcpStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrttUs        uint32                 `protobuf:"varint,1,opt,name=srtt_us,json=srttUs,proto3" json:"srtt_us,omitempty"`                      // smoothed RTT (microseconds)
	SndCwnd       uint32                 `protobuf:"varint,2,opt,name=snd_cwnd,json=sndCwnd,proto3" json:"snd_cwnd,omitempty"`                   // congestion window (packets)
	TotalRetrans  uint32                 `protobuf:"varint,3,opt,name=total_retrans,json=totalRetrans,proto3" json:"total_retrans,omitempty"`    // total retransmits for this connection
	PacketsOut    uint32                 `protobuf:"varint,4,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`          // packets in flight
	RetransOut    uint32                 `protobuf:"varint,5,opt,name=retrans_out,json=retransOut,proto3" json:"retrans_out,omitempty"`          // retransmitted packets outstanding
	LostOut       uint32                 `protobuf:"varint,6,opt,name=lost_out,json=lostOut,proto3" json:"lost_out,omitempty"`                   // lost packets
	RcvWnd        uint32                 `protobuf:"varint,7,opt,name=rcv_wnd,json=rcvWnd,proto3" json:"rcv_wnd,omitempty"`                      // receive window
	BytesSent     uint64                 `protobuf:"varint,8,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`             // total bytes sent
	BytesReceived uint64                 `protobuf:"varint,9,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"` // total bytes received
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpStats) Reset() {
	*x = TcpStats{}
	mi := &file_proto_rbscope_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpStats) ProtoMessage() {}

func (x *TcpStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpStats.ProtoReflect.Descriptor instead.
func (*TcpStats) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{13}
}

func (x *TcpStats) GetSrttUs() uint32 {
	if x != nil {
		return x.SrttUs
	}
	return 0
}

func (x *TcpStats) GetSndCwnd() uint32 {
	if x != nil {
		return x.SndCwnd
	}
	return 0
}

func (x *TcpStats) GetTotalRetrans() uint32 {
	if x != nil {
		return x.TotalRetrans
	}
	return 0
}

func (x *TcpStats) GetPacketsOut() uint32 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *TcpStats) GetRetransOut() uint32 {
	if x != nil {
		return x.RetransOut
	}
	return 0
}

func (x *TcpStats) GetLostOut() uint32 {
	if x != nil {
		return x.LostOut
	}
	return 0
}

func (x *TcpStats) GetRcvWnd() uint32 {
	if x != nil {
		return x.RcvWnd
	}
	return 0
}

func (x *TcpStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TcpStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type StackFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FunctionNameIdx uint32                 `protobuf:"varint,1,opt,name=function_name_idx,json=functionNameIdx,proto3" json:"function_name_idx,omitempty"` // index into string_table
	FileNameIdx     uint32                 `protobuf:"varint,2,opt,name=file_name_idx,json=fileNameIdx,proto3" json:"file_name_idx,omitempty"`             // index into string_table
	LineNumber      uint32                 `protobuf:"varint,3,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	FrameType       FrameType              `protobuf:"varint,4,opt,name=frame_type,json=frameType,proto3,enum=rbscope.FrameType" json:"frame_type,omitempty"` // Ruby, native, or cfunc
	Address         uint64                 `protobuf:"varint,5,opt,name=address,proto3" json:"address,omitempty"`                                             // raw instruction pointer (native frames only)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StackFrame) Reset() {
	*x = StackFrame{}
	mi := &file_proto_rbscope_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackFrame) ProtoMessage() {}

func (x *StackFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackFrame.ProtoReflect.Descriptor instead.
func (*StackFrame) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{14}
}

func (x *StackFrame) GetFunctionNameIdx() uint32 {
	if x != nil {
		return x.FunctionNameIdx
	}
	return 0
}

func (x *StackFrame) GetFileNameIdx() uint32 {
	if x != nil {
		return x.FileNameIdx
	}
	return 0
}

func (x *StackFrame) GetLineNumber() uint32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *StackFrame) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_TYPE_RUBY
}

func (x *StackFrame) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

// OTelContext links a sample or span to an OpenTelemetry trace.
type OTelContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                 // 16 bytes
	SpanId        []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`                    // 8 bytes
	ServiceIdx    uint32                 `protobuf:"varint,3,opt,name=service_idx,json=serviceIdx,proto3" json:"service_idx,omitempty"`       // index into string_table
	OperationIdx  uint32                 `protobuf:"varint,4,opt,name=operation_idx,json=operationIdx,proto3" json:"operation_idx,omitempty"` // index into string_table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTelContext) Reset() {
	*x = OTelContext{}
	mi := &file_proto_rbscope_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTelContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTelContext) ProtoMessage() {}

func (x *OTelContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbscope_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTelContext.ProtoReflect.Descriptor instead.
func (*OTelContext) Descriptor() ([]byte, []int) {
	return file_proto_rbscope_proto_rawDescGZIP(), []int{15}
}

func (x *OTelContext) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *OTelContext) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *OTelContext) GetServiceIdx() uint32 {
	if x != nil {
		return x.ServiceIdx
	}
	return 0
}

func (x *OTelContext) GetOperationIdx() uint32 {
	if x != nil {
		return x.OperationIdx
	}
	return 0
}

var File_proto_rbscope_proto protoreflect.FileDescriptor

const file_proto_rbscope_proto_rawDesc = "" +
	"\n" +
	"\x13proto/rbscope.proto\x12\arbscope\"\xf8\x01\n" +
	"\aCapture\x12.\n" +
	"\x06header\x18\x01 \x01(\v2\x16.rbscope.CaptureHeaderR\x06header\x12!\n" +
	"\fstring_table\x18\x02 \x03(\tR\vstringTable\x124\n" +
	"\vframe_table\x18\x03 \x03(\v2\x13.rbscope.StackFrameR\n" +
	"frameTable\x121\n" +
	"\athreads\x18\x04 \x03(\v2\x17.rbscope.ThreadTimelineR\athreads\x121\n" +
	"\n" +
	"categories\x18\x05 \x03(\v2\x11.rbscope.CategoryR\n" +
	"categories\"\xba\x02\n" +
	"\rCaptureHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12\"\n" +
	"\rstart_time_ns\x18\x05 \x01(\x04R\vstartTimeNs\x12\x1e\n" +
	"\vend_time_ns\x18\x06 \x01(\x04R\tendTimeNs\x12.\n" +
	"\x13sample_frequency_hz\x18\a \x01(\rR\x11sampleFrequencyHz\x12!\n" +
	"\fruby_version\x18\b \x01(\tR\vrubyVersion\x12'\n" +
	"\x0frbscope_version\x18\t \x01(\tR\x0erbscopeVersion\"D\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\xf2\x04\n" +
	"\x0eThreadTimeline\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\rR\bthreadId\x12*\n" +
	"\x11ruby_thread_value\x18\x02 \x01(\x04R\x0frubyThreadValue\x12&\n" +
	"\x0fthread_name_idx\x18\x03 \x01(\rR\rthreadNameIdx\x12)\n" +
	"\asamples\x18\x04 \x03(\v2\x0f.rbscope.SampleR\asamples\x12-\n" +
	"\tio_events\x18\x05 \x03(\v2\x10.rbscope.IOEventR\bioEvents\x126\n" +
	"\fsched_events\x18\x06 \x03(\v2\x13.rbscope.SchedEventR\vschedEvents\x123\n" +
	"\vspan_events\x18\a \x03(\v2\x12.rbscope.SpanEventR\n" +
	"spanEvents\x120\n" +
	"\n" +
	"gvl_events\x18\b \x03(\v2\x11.rbscope.GVLEventR\tgvlEvents\x12;\n" +
	"\vallocations\x18\t \x03(\v2\x19.rbscope.AllocationSampleR\vallocations\x124\n" +
	"\x06states\x18\n" +
	" \x03(\v2\x1c.rbscope.ThreadStateIntervalR\x06states\x12C\n" +
	"\x11gvl_state_changes\x18\v \x03(\v2\x17.rbscope.GVLStateChangeR\x0fgvlStateChanges\x12>\n" +
	"\rgvl_intervals\x18\f \x03(\v2\x19.rbscope.GVLStateIntervalR\fgvlIntervals\"\x99\x01\n" +
	"\x06Sample\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x1b\n" +
	"\tframe_ids\x18\x02 \x03(\rR\bframeIds\x127\n" +
	"\fotel_context\x18\x03 \x01(\v2\x14.rbscope.OTelContextR\votelContext\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\rR\x06weight\"\xd9\x03\n" +
	"\aIOEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x1f\n" +
	"\vsyscall_idx\x18\x02 \x01(\rR\n" +
	"syscallIdx\x12\x0e\n" +
	"\x02fd\x18\x03 \x01(\x05R\x02fd\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x04R\x05bytes\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x05 \x01(\x04R\tlatencyNs\x12\x1e\n" +
	"\vfd_info_idx\x18\x06 \x01(\rR\tfdInfoIdx\x12,\n" +
	"\x12nearest_sample_idx\x18\a \x01(\rR\x10nearestSampleIdx\x123\n" +
	"\x16caused_sched_event_idx\x18\b \x01(\rR\x13causedSchedEventIdx\x12.\n" +
	"\ttcp_stats\x18\t \x01(\v2\x11.rbscope.TcpStatsR\btcpStats\x12(\n" +
	"\afd_type\x18\n" +
	" \x01(\x0e2\x0f.rbscope.FdTypeR\x06fdType\x12\x1d\n" +
	"\n" +
	"local_port\x18\v \x01(\rR\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\f \x01(\rR\n" +
	"remotePort\x12(\n" +
	"\x10native_frame_ids\x18\r \x03(\rR\x0enativeFrameIds\"\xd0\x01\n" +
	"\n" +
	"SchedEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x1c\n" +
	"\n" +
	"off_cpu_ns\x18\x02 \x01(\x04R\boffCpuNs\x12-\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x15.rbscope.OffCPUReasonR\x06reason\x12'\n" +
	"\x10caused_by_io_idx\x18\x04 \x01(\rR\rcausedByIoIdx\x12)\n" +
	"\x11caused_by_gvl_idx\x18\x05 \x01(\rR\x0ecausedByGvlIdx\"\xe7\x01\n" +
	"\tSpanEvent\x12\x19\n" +
	"\bstart_ns\x18\x01 \x01(\x04R\astartNs\x12\x1f\n" +
	"\vduration_ns\x18\x02 \x01(\x04R\n" +
	"durationNs\x12#\n" +
	"\roperation_idx\x18\x03 \x01(\rR\foperationIdx\x12#\n" +
	"\rcomponent_idx\x18\x04 \x01(\rR\fcomponentIdx\x127\n" +
	"\fotel_context\x18\x05 \x01(\v2\x14.rbscope.OTelContextR\votelContext\x12\x1b\n" +
	"\tframe_ids\x18\x06 \x03(\rR\bframeIds\"\x9c\x01\n" +
	"\bGVLEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x17\n" +
	"\await_ns\x18\x02 \x01(\x04R\x06waitNs\x12(\n" +
	"\x10holder_thread_id\x18\x03 \x01(\rR\x0eholderThreadId\x12*\n" +
	"\x11holder_sample_idx\x18\x04 \x01(\rR\x0fholderSampleIdx\"\\\n" +
	"\x0eGVLStateChange\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.rbscope.GVLStateR\x05state\"m\n" +
	"\x10GVLStateInterval\x12\x19\n" +
	"\bstart_ns\x18\x01 \x01(\x04R\astartNs\x12\x15\n" +
	"\x06end_ns\x18\x02 \x01(\x04R\x05endNs\x12'\n" +
	"\x05state\x18\x03 \x01(\x0e2\x11.rbscope.GVLStateR\x05state\"\x99\x01\n" +
	"\x10AllocationSample\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12&\n" +
	"\x0fobject_type_idx\x18\x02 \x01(\rR\robjectTypeIdx\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1b\n" +
	"\tframe_ids\x18\x04 \x03(\rR\bframeIds\"\x9b\x01\n" +
	"\x13ThreadStateInterval\x12\x19\n" +
	"\bstart_ns\x18\x01 \x01(\x04R\astartNs\x12\x15\n" +
	"\x06end_ns\x18\x02 \x01(\x04R\x05endNs\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.rbscope.ThreadStateR\x05state\x12&\n" +
	"\x0fcause_event_idx\x18\x04 \x01(\rR\rcauseEventIdx\"\x9f\x02\n" +
	"\bTcpStats\x12\x17\n" +
	"\asrtt_us\x18\x01 \x01(\rR\x06srttUs\x12\x19\n" +
	"\bsnd_cwnd\x18\x02 \x01(\rR\asndCwnd\x12#\n" +
	"\rtotal_retrans\x18\x03 \x01(\rR\ftotalRetrans\x12\x1f\n" +
	"\vpackets_out\x18\x04 \x01(\rR\n" +
	"packetsOut\x12\x1f\n" +
	"\vretrans_out\x18\x05 \x01(\rR\n" +
	"retransOut\x12\x19\n" +
	"\blost_out\x18\x06 \x01(\rR\alostOut\x12\x17\n" +
	"\arcv_wnd\x18\a \x01(\rR\x06rcvWnd\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\b \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\t \x01(\x04R\rbytesReceived\"\xca\x01\n" +
	"\n" +
	"StackFrame\x12*\n" +
	"\x11function_name_idx\x18\x01 \x01(\rR\x0ffunctionNameIdx\x12\"\n" +
	"\rfile_name_idx\x18\x02 \x01(\rR\vfileNameIdx\x12\x1f\n" +
	"\vline_number\x18\x03 \x01(\rR\n" +
	"lineNumber\x121\n" +
	"\n" +
	"frame_type\x18\x04 \x01(\x0e2\x12.rbscope.FrameTypeR\tframeType\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\x04R\aaddress\"\x87\x01\n" +
	"\vOTelContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\x12\x1f\n" +
	"\vservice_idx\x18\x03 \x01(\rR\n" +
	"serviceIdx\x12#\n" +
	"\roperation_idx\x18\x04 \x01(\rR\foperationIdx*\x98\x01\n" +
	"\fOffCPUReason\x12\x13\n" +
	"\x0fOFF_CPU_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12OFF_CPU_IO_BLOCKED\x10\x01\x12\x14\n" +
	"\x10OFF_CPU_GVL_WAIT\x10\x02\x12\x11\n" +
	"\rOFF_CPU_MUTEX\x10\x03\x12\x15\n" +
	"\x11OFF_CPU_PREEMPTED\x10\x04\x12\x1b\n" +
	"\x17OFF_CPU_VOLUNTARY_SLEEP\x10\x05*h\n" +
	"\bGVLState\x12\x15\n" +
	"\x11GVL_STATE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11GVL_STATE_RUNNING\x10\x01\x12\x15\n" +
	"\x11GVL_STATE_STALLED\x10\x02\x12\x17\n" +
	"\x13GVL_STATE_SUSPENDED\x10\x03*\xae\x02\n" +
	"\vThreadState\x12\x18\n" +
	"\x14THREAD_STATE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14THREAD_STATE_RUNNING\x10\x01\x12\x1b\n" +
	"\x17THREAD_STATE_OFF_CPU_IO\x10\x02\x12\x1c\n" +
	"\x18THREAD_STATE_OFF_CPU_GVL\x10\x03\x12\x1e\n" +
	"\x1aTHREAD_STATE_OFF_CPU_MUTEX\x10\x04\x12\x1e\n" +
	"\x1aTHREAD_STATE_OFF_CPU_SLEEP\x10\x05\x12\"\n" +
	"\x1eTHREAD_STATE_OFF_CPU_PREEMPTED\x10\x06\x12 \n" +
	"\x1cTHREAD_STATE_OFF_CPU_UNKNOWN\x10\a\x12\x13\n" +
	"\x0fTHREAD_STATE_GC\x10\b\x12\x15\n" +
	"\x11THREAD_STATE_IDLE\x10\t*W\n" +
	"\x06FdType\x12\x0e\n" +
	"\n" +
	"FD_UNKNOWN\x10\x00\x12\v\n" +
	"\aFD_FILE\x10\x01\x12\n" +
	"\n" +
	"\x06FD_TCP\x10\x02\x12\n" +
	"\n" +
	"\x06FD_UDP\x10\x03\x12\v\n" +
	"\aFD_UNIX\x10\x04\x12\v\n" +
	"\aFD_PIPE\x10\x05*M\n" +
	"\tFrameType\x12\x13\n" +
	"\x0fFRAME_TYPE_RUBY\x10\x00\x12\x15\n" +
	"\x11FRAME_TYPE_NATIVE\x10\x01\x12\x14\n" +
	"\x10FRAME_TYPE_CFUNC\x10\x02B;Z9github.com/schlubbi/rbscope/collector/pkg/proto/rbscopepbb\x06proto3"

var (
	file_proto_rbscope_proto_rawDescOnce sync.Once
	file_proto_rbscope_proto_rawDescData []byte
)

func file_proto_rbscope_proto_rawDescGZIP() []byte {
	file_proto_rbscope_proto_rawDescOnce.Do(func() {
		file_proto_rbscope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbscope_proto_rawDesc), len(file_proto_rbscope_proto_rawDesc)))
	})
	return file_proto_rbscope_proto_rawDescData
}

var file_proto_rbscope_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_rbscope_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_rbscope_proto_goTypes = []any{
	(OffCPUReason)(0),           // 0: rbscope.OffCPUReason
	(GVLState)(0),               // 1: rbscope.GVLState
	(ThreadState)(0),            // 2: rbscope.ThreadState
	(FdType)(0),                 // 3: rbscope.FdType
	(FrameType)(0),              // 4: rbscope.FrameType
	(*Capture)(nil),             // 5: rbscope.Capture
	(*CaptureHeader)(nil),       // 6: rbscope.CaptureHeader
	(*Category)(nil),            // 7: rbscope.Category
	(*ThreadTimeline)(nil),      // 8: rbscope.ThreadTimeline
	(*Sample)(nil),              // 9: rbscope.Sample
	(*IOEvent)(nil),             // 10: rbscope.IOEvent
	(*SchedEvent)(nil),          // 11: rbscope.SchedEvent
	(*SpanEvent)(nil),           // 12: rbscope.SpanEvent
	(*GVLEvent)(nil),            // 13: rbscope.GVLEvent
	(*GVLStateChange)(nil),      // 14: rbscope.GVLStateChange
	(*GVLStateInterval)(nil),    // 15: rbscope.GVLStateInterval
	(*AllocationSample)(nil),    // 16: rbscope.AllocationSample
	(*ThreadStateInterval)(nil), // 17: rbscope.ThreadStateInterval
	(*TcpStats)(nil),            // 18: rbscope.TcpStats
	(*StackFrame)(nil),          // 19: rbscope.StackFrame
	(*OTelContext)(nil),         // 20: rbscope.OTelContext
}
var file_proto_rbscope_proto_depIdxs = []int32{
	6,  // 0: rbscope.Capture.header:type_name -> rbscope.CaptureHeader
	19, // 1: rbscope.Capture.frame_table:type_name -> rbscope.StackFrame
	8,  // 2: rbscope.Capture.threads:type_name -> rbscope.ThreadTimeline
	7,  // 3: rbscope.Capture.categories:type_name -> rbscope.Category
	9,  // 4: rbscope.ThreadTimeline.samples:type_name -> rbscope.Sample
	10, // 5: rbscope.ThreadTimeline.io_events:type_name -> rbscope.IOEvent
	11, // 6: rbscope.ThreadTimeline.sched_events:type_name -> rbscope.SchedEvent
	12, // 7: rbscope.ThreadTimeline.span_events:type_name -> rbscope.SpanEvent
	13, // 8: rbscope.ThreadTimeline.gvl_events:type_name -> rbscope.GVLEvent
	16, // 9: rbscope.ThreadTimeline.allocations:type_name -> rbscope.AllocationSample
	17, // 10: rbscope.ThreadTimeline.states:type_name -> rbscope.ThreadStateInterval
	14, // 11: rbscope.ThreadTimeline.gvl_state_changes:type_name -> rbscope.GVLStateChange
	15, // 12: rbscope.ThreadTimeline.gvl_intervals:type_name -> rbscope.GVLStateInterval
	20, // 13: rbscope.Sample.otel_context:type_name -> rbscope.OTelContext
	18, // 14: rbscope.IOEvent.tcp_stats:type_name -> rbscope.TcpStats
	3,  // 15: rbscope.IOEvent.fd_type:type_name -> rbscope.FdType
	0,  // 16: rbscope.SchedEvent.reason:type_name -> rbscope.OffCPUReason
	20, // 17: rbscope.SpanEvent.otel_context:type_name -> rbscope.OTelContext
	1,  // 18: rbscope.GVLStateChange.state:type_name -> rbscope.GVLState
	1,  // 19: rbscope.GVLStateInterval.state:type_name -> rbscope.GVLState
	2,  // 20: rbscope.ThreadStateInterval.state:type_name -> rbscope.ThreadState
	4,  // 21: rbscope.StackFrame.frame_type:type_name -> rbscope.FrameType
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_rbscope_proto_init() }
func file_proto_rbscope_proto_init() {
	if File_proto_rbscope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbscope_proto_rawDesc), len(file_proto_rbscope_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rbscope_proto_goTypes,
		DependencyIndexes: file_proto_rbscope_proto_depIdxs,
		EnumInfos:         file_proto_rbscope_proto_enumTypes,
		MessageInfos:      file_proto_rbscope_proto_msgTypes,
	}.Build()
	File_proto_rbscope_proto = out.File
	file_proto_rbscope_proto_goTypes = nil
	file_proto_rbscope_proto_depIdxs = nil
}
