apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbscope-collector
  namespace: rbscope
  labels:
    app: rbscope-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbscope-collector
  labels:
    app: rbscope-collector
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbscope-collector
  labels:
    app: rbscope-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbscope-collector
subjects:
  - kind: ServiceAccount
    name: rbscope-collector
    namespace: rbscope
